### ISSUE TITLE
🤡

### ISSUE THREAD

**Issue by TranCongVinh** [NotAHero04/EveryCode#1]
🤡 = 🤡 ?

**Comment by NotAHero04** [comment]
your brain can answer that faster than me.

**Comment by rscDoesMoreTrolling** [comment]
> 🤡 = 🤡 ?

haha you clown

**Comment by GoneSubject1** [comment]
wha

**Comment by TranCongVinh** [comment]
![image](https://user-images.githubusercontent.com/90259221/151756555-03573767-b92b-41bf-9e13-d6a987cd46a9.png)
![image](https://user-images.githubusercontent.com/90259221/151756576-ec4f2303-428f-4d07-92dc-7ea59065710d.png)

**Comment by GoneSubject1** [comment]
> ![image](https://user-images.githubusercontent.com/90259221/151756555-03573767-b92b-41bf-9e13-d6a987cd46a9.png)
> ![image](https://user-images.githubusercontent.com/90259221/151756576-ec4f2303-428f-4d07-92dc-7ea59065710d.png)
> 

yes delete it when

**Comment by GoneSubject1** [comment]
imagine hung pin this issue
